onlineshop/cart/urls.py
from django.urls import path

from .views import *

app_name = 'cart'

urlpatterns = [
    path('', detail, name='detail'),
    path('add/<int:product_id>', add, name='product_add'),
]

onlineshop/config/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls')),
    path('', include('shop.urls')),
]


onlineshop/shop/urls.py
from django.urls import path
from .views import *

app_name = 'shop' # 네임스페이스

urlpatterns = [
    path('', product_in_category, name = 'product_all'),
    path('<slug:category_slug>/', product_in_category, name = 'product_in_category'),
    path('<int:id>/<product_slug>/', product_detail, name = 'product_detail'),

]

onlineshop/cart/models.py
from django.db import models

# Create your models here.

onlineshop/shop/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length = 200, db_index = True)
    meta_description = models.TextField(blank = True)
    slug = models.SlugField(max_length = 200, unique = True, db_index = True, allow_unicode=True) # 언더바가 들어가는 형태

    class Meta: # 이 클래스 밖에선 쓸 수 없는 inner클래스?
        ordering = ['name']
        verbose_name = 'category' # 단수형 (관리자 모드에서 사용)
        verbose_name_plural = 'categories' # 복수형 (관리자 모드에서 사용)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_in_category', args = [self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete = models.SET_NULL, null = True, related_name = 'products')
    name = models.CharField(max_length = 200, db_index = True)
    slug =  models.SlugField(max_length = 200, db_index = True, unique=True, allow_unicode=True)

    image = models.ImageField(upload_to = 'products/%Y/%m/%d', blank = True)
    description = models.TextField(blank = True) # blank: valid함수가 무시하게 만드는 함수
    meta_description = models.TextField(blank = True)

    price = models.DecimalField(max_digits = 10, decimal_places = 2) # 10진수 필드, decimal_places: 소수점 자리수
    stock = models.PositiveIntegerField() # 양수값만 들어오는 필드

    available_display = models.BooleanField('Display', default = True)
    available_order = models.BooleanField('Order', default = True)

    created = models.DateTimeField(auto_now_add = True) # 최초생성날짜 유지
    updated = models.DateTimeField(auto_now = True) # 업데이트시 날짜 갱신

    class Meta:
        ordering = ['-created']
        index_together = [['id', 'slug']] # 외부대괄호: 문법, 내부대괄호: 리스트

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args = [self.id, self.slug])

onlineshop/cart/forms.py
from django import forms # 폼을 만드는 클래스

class AddProductForm(forms.Form):
    quantity = forms.IntegerField()
    is_update = forms.BooleanField(required = False,
                                   initial = False, widget = forms.HiddenInput)
    # 넘길 값으로 폼 안에 넣어야 하는데 화면에는 숨기고 싶을 때 HiddenInput사용
    # HTML에서는 <input type="hidden"> 방식으로 숨김


onlineshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from shop.models import Product
from .forms import AddProductForm
from .cart import Cart


@require_POST
def add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    form = AddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], is_update=cd['is_update'])

    return redirect('cart:detail')

def remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:detail')


def detail(request):
    cart = Cart(request)
    for product in cart:
        product['quantity_form'] = AddProductForm(initial={'quantity':product['quantity'], 'is_update':True})
    return render(request, 'cart/detail.html', {'cart':cart})

onlineshop/shop/views.py
from django.shortcuts import render, get_object_or_404

from cart.forms import AddProductForm
from .models import *

# Create your views here.
# 모든 카테고리 출력
# 해당 카테고리 클릭하면 출력
def product_in_category(request, category_slug=None): # category_slug값이 있으면 값을 받고, 없으면 None을 default값으로 지정
    # DB검색 결과를 템플릿에 넘겨줌
    # map형태로 만들어서 넘겨줌
    current_category = None # 현재 선택된 카테고리

    # category없이 전체 출력
    categories = Category.objects.all() # 카테고리 전체 목록 select
    products = Product.objects.filter(available_display = True) # 모든 카테고리의 상품 목록 select

    # category에 해당하는 것만 출력
    if category_slug: # category_slug에
        current_category = get_object_or_404(Category, slug = category_slug) # 값이 있으면 가져오고 없으면 404처리해주는 함수
        products = products.filter(category = current_category) # 선택된 카테고리에 해당하는 상품만 select

    return render(request, 'shop/list.html', {
        'current_category' : current_category,
        'products' : products,
        'categories' : categories})


# 제품 상세페이지 출력
def product_detail(request, id, product_slug=None):
    product = get_object_or_404(Product, id=id, slug=product_slug)
    add_to_cart = AddProductForm(initial = {'quantity':1})

    return render(request, 'shop/detail.html', {'product':product, 'add_to_cart':add_to_cart})


onlineshop/cart/templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Shopping Cart{% endblock %}
{% block content %}
<table class="table table-striped">
    <thead align="center">
    <tr>
        <th scope="col" width="15%">이미지</th>
        <th scope="col">제품명</th>
        <th scope="col">제품개수</th>
        <th scope="col" width="15%">제거하기</th>
        <th scope="col" width="20%">개당 가격</th>
        <th scope="col" width="20%">제품 총 가격</th>
    </tr>
    </thead>
    <tbody>
    {% for item in cart %}
    {% with product=item.product %}
    <tr>
        <th scope="row">
            <a href="{{product.get_absolute_url}}">
                <img src="{{product.image.url}}" class="img-thumbnail">
            </a>
        </th>
        <td>{{product.name}}</td>
        <td>
            <form action="{% url 'cart:product_add' product.id %}" method="post">
                {{item.quantity_form.quantity}}
                {{item.quantity_form.is_update}}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" value="수정">
            </form>
        </td>
        <td>Remove</td>
        <td class="num" align="right">{{ item.price }}원</td>
        <td class="num" align="right">{{ item.total_price }}원</td>
    </tr>
    {% endwith %}
    {% endfor %}
    <tr class="total">
        <td colspan="2"></td>
        <td colspan="2" align="right">총 결제금액</td>
        <td colspan="2" class="num" align="right">{{ cart.get_total_price|floatformat:"2" }}원</td>
    </tr>
    </tbody>
</table>
<p class="text-right">
    <a href='{% url "shop:product_all" %}' class="btn btn-secondary">계속 쇼핑하기</a>
</p>
{% endblock %}

onlineshop/shop/templates/shop/detail.html
{% extends 'base.html' %}
{% block title %}Product Detail{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-4">
                <img src="{{product.image.url}}" width="100%">
            </div>
            <div class="col">
                <h1 class="display-6">{{product.name}}</h1>
                <p><span class="badge badge-secondary">가격</span>{{product.price}}</p>
                <form action="{% url 'cart:product_add' product.id %}" method="post">
                    {{add_to_cart}}
                    {% csrf_token %}
                    <input type="submit" class="btn btn-primary btn-sm" value="장바구니에 담기">
                </form>
                <h5><span class="badge badge-secondary">제품설명</span>{{product.description|linebreaks}}</h5>
            </div>
        </div>
    </div>
{% endblock %}

onlineshop/shop/templates/shop/list.html
{% extends 'base.html' %}

{% block title %} 전체 리스트 페이지 {% endblock %}

{% block content %}
<div class="row">
    <div class="col-3">
        <div class="list-group">
            <a href="/" class="list-group-item {% if not current_category %}active{% endif %}">All</a> <!-- 카테고리 선택되지 않은 경우 All이 활성화 -->
            {% for c in categories %}
                <a href="{{c.get_absolute_url}}" class="list-group-item {% if current_category.slug == c.slug %}active{% endif %}">{{c.name}}</a> <!-- 선택된 카테고리가 활성화 -->
            {% endfor %}
        </div>
    </div>
    <div class="col">
        <div class="alert alert-info" role="alert">
            {% if current_category %}{{current_category.name}}{% else %}All Products{% endif %}
        </div>
        <div class="row">
            {% for product in products %}
                <div class="col-4">
                    <div class="card">
                        <img class="card-img-top" src="{{product.image.url}}" alt="{{product.name}}">
                        <div class="card-body">
                            <h5 class="card-title">{{product.name}}</h5>
                            <p class="card-text">{{product.description}} <span class="badge badge-secondary">{{product.price}}원</span> </p>
                            <a href="{{product.get_absolute_url}}" class="btn btn-sm btn-primary">자세히 보기</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}