Dstragram/photo/urls.py
from django.urls import path
from .views import *
from .models import *
app_name = 'photo'
urlpatterns = [
    path('', photo_list, name='photo_list'),
    path('detail/<int:pk>', DetailView.as_view(model = Photo, template_name = 'photo/detail.html'), name='photo_detail'), # 짧은 뷰는 views.py 대신 여기에 넣어도 됨    path('upload/', PhotoUploadView.as_view(), name = 'photo_upload'),
    path('update/<int:pk>', PhotoUpdateView.as_view(), name = 'photo_update'),
    path('delete/<int:pk>', PhotoDelete.as_view(), name = 'photo_delete'),
    path('upload/', PhotoUploadView.as_view(), name='photo_upload'),
]

Dstragram/photo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.



class Photo(models.Model):
    author = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'user_photos') # 외래키 CASCADE
    photo = models.ImageField(upload_to = 'photos/%Y/%m/%d', default = 'photos/no_image.png') # 파일 업로드
    text = models.TextField() # 긴 글?
    created = models.DateTimeField(auto_now_add = True) # auto_now_add: 최초 레코드 생성 일시 고정
    updated = models.DateTimeField(auto_now = True) # auto_now: save할 때마다 수정 일시 업데이트

    class Meta: # 클래스 안의 클래스는 많이 사용되는 방법은 아님. 상위 클래스에 종속적.
        ordering = ['-updated']

    def __str__(self):
        return self.author.username + " " + self.created.strftime('%Y-%m-%d %H:%M')

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=[str(self.id)])

Dstragram/photo/views.py
from django.shortcuts import *
from django.views.generic import *
from .models import Photo

# Create your views here.

# 전체 검색: 함수
def photo_list(request):
    photos = Photo.objects.all()
    return render(request, 'photo/list.html', {'photos':photos})

# 사진 업로드
class PhotoUploadView(CreateView):
    model = Photo
    fields = ['photo', 'text']
    template_name = 'photo/upload.html'

    def form_valid(self, form): # 로그인 된 유저인지 확인
        form.instance.author_id = self.request.user.id
        if form.is_valid(): # 로그인 중인 경우
            form.instance.save() # 사진 업로드 commit
            return redirect('/') # 완료 후 메인 페이지로 돌아감
        else: # 로그아웃 상태인 경우
            return self.render_to_response({'form':form}) # 어디로 돌아가누

# 사진 삭제
class PhotoDelete(DeleteView):
    model = Photo
    success_url = '/'
    template_name = 'photo/delete.html'

# 사진 변경
class PhotoUpdateView(UpdateView):
    model = Photo
    fields = ['photo', 'text']
    template_name = 'photo/update.html'

Dstragram/photo/templates/photo/delete.html
{% extends 'base.html' %}
{% block title %} - List {% endblock %}
{% block menu1 %}info{% endblock %}
{% block menu2 %}info{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-2"><br></div>
    <div class="col-md-8 panel panel-default jumbotron">
        <div class="alert alert-info">
            정말로 삭제하시겠습니까 {{object}}?
        </div>
        <form action="" method="post" enctype="multipart/form-data"> <!-- 텍스트 말고도 다양한 파일 형태 -->
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="삭제">
        </form>
    </div>
</div>
{% endblock %}

Dstragram/photo/templates/photo/detail.html
{% extends 'base.html' %}
{% block title %} - Detail {% endblock %}
{% block menu1 %}info{% endblock %}
{% block menu2 %}info{% endblock %}
{% block content %}
<div class="containter">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 panel panel-default jumbotron">
            <p><img src="{{object.photo.url}}" style="width:100%;"></p> <!-- 사진 표시 -->
            <button type="button" class="btn btn-xs btn-outline-info disabled">
                {{object.author.username}}
            </button>
            <p>{{object.text|linebreaksbr}}</p> <!-- 사진에 첨부된 글 표시 -->
            <a href="{% url 'photo:photo_delete' pk=object.id %}"
               class="btn btn-danger btn float-right">삭제</a>
            <a href="{% url 'photo:photo_update' pk=object.id %}"
               class="btn btn-success btn float-right" style="margin:0 10px;">수정</a>
        </div>
    </div>
    <!-- 댓글 위치 -->
    <div class="row">
        <div class="col-md-2"><br><br></div>
        <div class="col-md-8 panel panel-default">
            {% load disqus_tags %}
            {% disqus_show_comments %}
        </div>
    </div>
</div>
{% endblock %}

Dstragram/photo/templates/photo/list.html
{% extends 'base.html' %}
{% block title %} - List {% endblock %}
{% block menu1 %}white{% endblock %}
{% block menu2 %}info{% endblock %}
{% block content %}
{% for post in photos %}
<br>
<div class="row">
    <div class="col-md-2"><br></div>
    <div class="col-md-8 panel panel-default jumbotron">
        <p><img src="{{post.photo.url}}" style="width:100%;"></p> <!-- 사진 표시 -->
        <button type="button" class="btn btn-xs btn-outline-info disabled">
            {{post.author.username}}
        </button><br><br>
        <p>{{post.text|linebreaksbr}}</p> <!-- 사진에 첨부된 글 표시 -->
        <p class="text-right">
            <a href="{% url 'photo:photo_detail' pk=post.id %}"
            class="btn btn-xs btn-success">댓글달기</a>
        </p>
    </div>
</div>
<br>
{% endfor %}
{% endblock %}

Dstragram/photo/templates/photo/update.html
{% extends 'base.html' %}
{% block title %} - List {% endblock %}
{% block menu1 %}info{% endblock %}
{% block menu2 %}info{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-2"><br></div>
    <div class="col-md-8 panel panel-default jumbotron">
        <div class="alert alert-info">
            정말로 수정하시겠습니까 {{object}}?
        </div>
        <form action="" method="post" enctype="multipart/form-data"> <!-- 텍스트 말고도 다양한 파일 형태 -->
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" class="btn btn-success" value="수정">
        </form>
    </div>
</div>
{% endblock %}

Dstragram/photo/templates/photo/upload.html
{% extends 'base.html' %}
{% block title %} - List {% endblock %}
{% block menu1 %}info{% endblock %}
{% block menu2 %}white{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-2"><br></div>
    <div class="col-md-8 panel panel-default jumbotron">
        <form action="" method="post" enctype="multipart/form-data"> <!-- 텍스트 말고도 다양한 파일 형태 -->
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="올리기">
        </form>
    </div>
</div>
{% endblock %}