Dstragram/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('photo.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

from django.conf.urls.static import static
from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Dstragram/photo/urls.py
from django.urls import path
from .views import *
from .models import *
app_name = 'photo'
urlpatterns = [
    path('', photo_list, name='photo_list'),
    path('detail/<int:pk>', DetailView.as_view(model = Photo, template_name = 'photo/detail.html'), name='photo_detail'), # 짧은 뷰는 views.py 대신 여기에 넣어도 됨    path('upload/', PhotoUploadView.as_view(), name = 'photo_upload'),
    path('update/<int:pk>', PhotoUpdateView.as_view(), name = 'photo_update'),
    path('delete/<int:pk>', PhotoDelete.as_view(), name = 'photo_delete'),
    path('upload/', PhotoUploadView.as_view(), name='photo_upload'),
]

Dstragram/photo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.



class Photo(models.Model):
    author = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'user_photos') # 외래키 CASCADE
    photo = models.ImageField(upload_to = 'photos/%Y/%m/%d', default = 'photos/no_image.png') # 파일 업로드
    text = models.TextField() # 긴 글?
    created = models.DateTimeField(auto_now_add = True) # auto_now_add: 최초 레코드 생성 일시 고정
    updated = models.DateTimeField(auto_now = True) # auto_now: save할 때마다 수정 일시 업데이트

    class Meta: # 클래스 안의 클래스는 많이 사용되는 방법은 아님. 상위 클래스에 종속적.
        ordering = ['-updated']

    def __str__(self):
        return self.author.username + " " + self.created.strftime('%Y-%m-%d %H:%M')

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=[str(self.id)])

Dstragram/photo/views.py
from django.shortcuts import *
from django.views.generic import *
from .models import Photo

# Create your views here.

# 전체 검색: 함수
def photo_list(request):
    photos = Photo.objects.all()
    return render(request, 'photo/list.html', {'photos':photos})

# 사진 업로드
class PhotoUploadView(CreateView):
    model = Photo
    fields = ['photo', 'text']
    template_name = 'photo/upload.html'

    def form_valid(self, form): # 로그인 된 유저인지 확인
        form.instance.author_id = self.request.user.id
        if form.is_valid(): # 로그인 중인 경우
            form.instance.save() # 사진 업로드 commit
            return redirect('/') # 완료 후 메인 페이지로 돌아감
        else: # 로그아웃 상태인 경우
            return self.render_to_response({'form':form}) # 어디로 돌아가누

# 사진 삭제
class PhotoDelete(DeleteView):
    model = Photo
    success_url = '/'
    template_name = 'photo/delete.html'

# 사진 변경
class PhotoUpdateView(UpdateView):
    model = Photo
    fields = ['photo', 'text']
    template_name = 'photo/update.html'

Dstragram/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet"
     href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
     integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
     crossorigin="anonymous"> <!-- 부트스트랩 css -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
     integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
     crossorigin="anonymous"></script> <!-- 제이쿼리 -->
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
     integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
     crossorigin="anonymous"></script> <!-- 에이젝스 -->
     <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
     integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"></script> <!-- 부트스트랩 js -->
    <title>Dstagram {% block title %}{% endblock %}</title>
    {% load static %}
</head>
<body>
<div class="container">
    <!-- 상단 네이게이션 메뉴바 -->
    <header class="header clearfix">
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a href="/" class="navbar-brand">Dstagram</a> <!-- 브랜드 명 -->
            <ul class="nav">

                <li class="nav-item active"> <!-- 홈으로 가기 -->
                    <a href="/" class="nav-link bg-info border border-{% block menu1 %}white{% endblock %}" style="color:white;">HOME</a>
                </li>
                {% if user.is_authenticated %} <!-- 로그인여부 확인 -->
                <li class="nav-item"> <!-- 사진 업로드 버튼 -->
                    <a href="{% url 'photo:photo_upload' %}" class="nav-link bg-info border border-{% block menu2 %}info{% endblock %}" style="color:white;">사진올리기</a>
                </li>
                <li class="nav-item"> <!-- 로그인한 사용자 환영 문구 -->
                    <a href="#" class="nav-link" style="color:#e1e6ef;">{{user.get_username}}님</a> <!-- 이름 불러오기 -->
                </li>
                <li class="nav-item">
                    <a class="nav-link bg-info" href="{% url 'account_logout' %}" style="color:white;">로그아웃</a>
                </li>
                {% else %}
                <li>
                    <a class="nav-link" href="{% url 'account_login' %}" style="color:white;">로그인</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </header>

    <!-- 우리가 넣고 싶은 내용 -->
    {% block content %}
    {% endblock %}

    <!-- 하단 메뉴 -->
    <footer>
        <hr color="red" width="100%">
        <p align="center">ⓒ 2019 Copyright KGITBANK™</p>
    </footer>
</div>
</body>
</html>