django8/member/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('readall/', views.Readall.as_view(), name='readall'),
    path('read/<int:pk>', views.Read.as_view(), name='read'),
    path('create/', views.Create.as_view(), name='create'),
    path('update/<int:pk>', views.Update.as_view(), name='update'),
    path('delete/<int:pk>', views.Delete.as_view(), name='delete'),

]

django8/member/models.py
from django.db import models
from django.urls import reverse
import datetime
# Create your models here.
class Member(models.Model):
    name = models.CharField(max_length = 20)
    tel = models.CharField(max_length = 30)
    addr = models.CharField(max_length = 100)

    def get_absolute_url(self):
        return reverse('detail', args = [str(self.pk)])

    def __str__(self):
        return self.name + ", " + self.tel + ", " + self.addr

class Board(models.Model):
    name = models.CharField(max_length = 20)
    title = models.CharField(max_length = 50)
    content = models.CharField(max_length = 2048)
    write_time = models.DateTimeField('date published')

    def get_absolute_url(self) :
        return reverse('detail', args = [str(self.pk)])

    def __str__(self):
        return self.name + ", " + self.title + ", " + self.content + ", " + str(self.write_time)

django8/member/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Member, Board
from django.views.generic import *
from django.urls import reverse_lazy


# Create your views here.


def index(reqeust):
    return HttpResponse('<a href=member/readall>게시판 입장</a>')


class Readall(ListView):
    model = Board
    template_name = 'member/readall.html'
    paginate_by = 5

class Read(DetailView):
    model = Board
    template_name = 'member/read.html'

class Create(CreateView):
    model = Board
    fields = ['name', 'title', 'content', 'write_time']
    success_url = reverse_lazy('readall')
    template_name = 'member/create.html'

class Update(UpdateView):
    model = Board
    fields = ['name', 'title', 'content', 'write_time']
    success_url = reverse_lazy('readall')
    template_name = 'member/update.html'

class Delete(DeleteView):
    model = Board
    success_url = reverse_lazy('readall')
    template_name = 'member/delete.html'

django8/member/templates/member/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>글 작성하기</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="글쓰기">
</form>
</body>
</html>

django8/member/templates/member/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>글 삭제하기</title>
</head>
<body>
<h2> 정말 삭제하시겠습니까? </h2>
<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="삭제">
</form>
<a href="/member/readall">취소</a>
</body>
</html>

django8/member/templates/member/read.html
<!DOCTYPE html>
<html lang="en">
<body>
<head>
    <meta charset="UTF-8">
    <title>게시판 글 상세보기</title>
</head>
<div width="500">
    <table width="500" border="1">
        <tr>
            <td>번호</td>
            <td>{{object.id}}</td>
        </tr>
        <tr>
            <td>제목</td>
            <td>{{object.title}}</td>
        </tr>
        <tr>
            <td>작성자</td>
            <td>{{object.name}}</td>
        </tr>
        <tr>
            <td>작성시간</td>
            <td>{{object.write_time}}</td>
        </tr>
        <tr>
            <td colspan="2">{{object.content}}</td>
        </tr>
    </table>
    <a href="/member/readall">목록</a>
    <a href="/member/delete/{{object.id}}">삭제</a>
    <a href="/member/update/{{object.id}}">수정</a>
</div>
</body>
</html>

django8/member/templates/member/readall.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>게시판 글 목록</title>
    {% load static %}
<!--    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css'%}">
<!--    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>-->
</head>
<body>
<div width="500">
    <table class="table table-striped" width="500">
        <thead class="thead thead-dark">
        <tr align="center">
            <th>번호</th>
            <th>제목</th>
            <th>작성자</th>
            <th>작성시간</th>
        </tr>
        </thead>
        <tbody>
        {% for board in board_list %}
        <tr align="center">
            <td>{{board.id}}</td>
            <td><a href="/member/read/{{board.id}}">{{board.title}}</a></td>
            <td>{{board.name}}</td>
            <td>{{board.write_time}}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <a class="btn btn-primary float-right" href="/member/create">글쓰기</a>
    <!-- 페이징 처리 -->
    {% block pagination %} <!-- 전체 블록: 부모템플릿에서 각종 함수/변수 override -->
        {% if is_paginated %} <!-- views.py에서 paganated가 되어 있다면 -->
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %} <!-- 이전버튼 -->
                    <li class="page-item">
                        <a class="page-link" href="{{request.path}}?page={{page_obj.previous_page_number}}">이전</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">이전</a>
                    </li>
                {% endif %}

                {% for object in page_obj.paginator.page_range %} <!-- 페이지 개수만큼 불러오기 -->
                    <li class="page-item {% if page_obj.number == forloop.counter %} active {% endif %}">
                        <a class="page-link" href="{{request.path}}?page={{forloop.counter}}">{{forloop.counter}}</a>
                    </li>
                {% endfor %}

                {% if page_obj.has_next %} <!-- 다음버튼 -->
                    <li class="page-item">
                        <a class="page-link" href="{{request.path}}?page={{page_obj.next_page_number}}">다음</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">다음</a>
                    </li>
                {% endif %}
            </ul>
        {% else %}
        {% endif %}
    {% endblock %}
</div>
</body>
</html>

django8/member/templates/member/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
adfasdfkljsdflk
</body>
</html>

django8/member/templates/member/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>글 수정하기</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="수정">
</form>
</body>
</html>